language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
  - npm install -g coveralls istanbul
  
script:
  - istanbul cover node_modules/mocha/bin/_mocha test

after_script:
  - cat ./coverage/lcov.info | coveralls